### ISSUE TITLE
Add a proxy support

### ISSUE THREAD

**Issue by kop** [tomsteele/node-yandex-search#1]
Hi. First of all, thanks for a nice module.

As Yandex XML API have very strong limitation to the requester IP address, it would be very nice to have an ability to set the proxy details for the request. As I understand, it should be easy - just add corresponding fields to the `options` object and pass them to the `request` module?

**Comment by tomsteele** [comment]
Alright you can pass in a proxy option in options now, going to publish 1.0.0.
